# =============================================================================
# SYSTEM JOB EXAMPLE - Traefik Ingress Controller
# =============================================================================
# System jobs run on EVERY node in the cluster automatically.
# When new nodes join, Nomad deploys this job to them too.
#
# Traefik is a reverse proxy that automatically discovers Nomad services
# and routes traffic to them based on tags (like path or hostname rules).
#
# Use cases for system jobs: load balancers, monitoring agents, log collectors.
#
# Access:
#   Web traffic:  http://<any-server-ip>  (port 80)
#   Dashboard:    http://<any-server-ip>:8081/dashboard/
# =============================================================================

job "traefik" {
  datacenters = ["dc1"]

  # "system" type = run one instance on EVERY node in the cluster
  # No "count" needed - Nomad handles placement automatically
  type = "system"

  group "traefik" {
    network {
      # Traefik listens on port 80 for web traffic
      port "http" {
        static = 80
      }
      # Dashboard for monitoring routes
      port "dashboard" {
        static = 8081
      }
    }

    # Register Traefik itself as a Nomad service
    service {
      name     = "traefik-http"
      provider = "nomad"
      port     = "http"
    }

    task "traefik" {
      driver = "docker"

      config {
        image        = "traefik:v3.3"
        network_mode = "host"
        ports        = ["http", "dashboard"]

        volumes = [
          "local/traefik.yaml:/etc/traefik/traefik.yaml",
        ]
      }

      # Traefik configuration - generated by Nomad template
      template {
        destination = "local/traefik.yaml"
        data        = <<-EOF
# Traefik Static Configuration

# Entry points - where Traefik listens for incoming traffic
entryPoints:
  web:
    address: ":80"
  dashboard:
    address: ":8081"

# API and Dashboard - view all routes at :8081/dashboard/
api:
  dashboard: true
  insecure: true

# Nomad service discovery - Traefik auto-discovers services
# No need for Consul - Traefik reads directly from Nomad API
providers:
  nomad:
    endpoint:
      address: http://{{ env "attr.unique.network.ip-address" }}:4646
    exposedByDefault: false
    prefix: traefik

# Logging
log:
  level: INFO
EOF
      }

      resources {
        cpu    = 100
        memory = 128
      }
    }
  }
}


